# Generated by Django 3.1.3 on 2020-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_auto_20201127_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apron',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='face_shield',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hand_sanitizer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hazmat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='masker_medis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='masker_n95',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sarung_tangan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sepatu_boots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
