# Generated by Django 3.1.3 on 2020-12-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_profilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
